package com.cricketAnalyzer;

public enum SortedField {
    AVERAGE,STRIKE_RATE,SORT_ON_6_AND_4,
    STRIKE_RATE_WITH_6_AND_4,AVERAGE_AND_STRIKE_RATE,RUN_WITH_AVERAGE,
    ECONOMY, STRIKE_RATE_WITH_5Wicket_AND_4Wicket,
    MAXIMUM_WICKET_AND_AVERAGE;
}
